import React from 'react'

export const Biography = () => {
    return (
        <>
            <h1 >Biografía</h1>
            <h3 className="flow-text">
                Transcurrieron 4 años. Cuatro años de ver, día tras día, la materialización de un sueño al lograr conducir un programa de radio en horario prime time en una de las principales emisoras de Venezuela. Parece poco, pero hay que ver que cuatro años se traducen en al menos unas 1.040 ediciones, debidamente producidas, conducidas y sobre todo, vividas, sentidas.
                Esta experiencia es la de Rebeca Liscano Trejo, una joven venezolana de 34 años de edad, que como toda chica de su época dedicó su vida a estudiar para lograr grandes cosas en lo que, sin duda alguna, es su pasión: los medios de comunicación.
                Rebeca estudió Marketing. Más tarde complementó su perfil titulándose como locutora. Con esta formación y con el carisma de esta talentosa joven, el futuro de Rebeca se perfilaba brillante en su país. 
                Fueron varias las experiencias profesionales en su natal Isla de Margarita. Todas satisfactorias, llenas de vivencias increíbles. Rebeca tuvo el privilegio de ser la presentadora de Caribe Genuino TV, un espacio transmitido a través de Telecaribe, en el que destacaba el potencial turístico de la Isla y exhibía con orgullo las playas en las que creció y jugó con los hermanos y primos, que hoy están lejos.
                Su carrera como locutora se iba consolidando. No pasó mucho tiempo cuando inició uno de sus más grandes proyectos: ‘Lo que viene conviene’. Se trataba de su propio programa de radio, transmitido en frecuencia modulada (FM) mediante la emisora Unión Radio, una de las más importantes de Venezuela. Durante el espacio, Liscano acostumbraba a hacer análisis, entrevistas y comentarios –cargados de veracidad- sobre la situación en el país. Quería ser optimista, pero ya para el período en el que tuvo su programa (2009 – 2013) era imposible dejar de palpar la realidad venezolana. Una decadencia que, para entonces, apenas mostraba sus más sutiles pinceladas en comparación con la tragedia que actualmente vive ese país.
                “Nunca fui extremista, simplemente conté las noticias reales, lo que estaba sucediendo y analizábamos lo que se venía… esa avalancha o tsunami que sea veía al fondo y que se comparaba con gobiernos de otros países, otras dictaduras y otras situaciones similares que la gente parece olvidar”, dijo Liscano, aún con cierta melancolía.   
                Se preguntarán por qué con melancolía si estaba cumpliendo un sueño, un sueño que compartió con miles de venezolanos que la escuchaban de lunes a viernes. Y es que en 2013, cuando Rebeca llegó a la radio, como lo hacía de costumbre, recibió una carta emitida por la Comisión Nacional de Telecomunicaciones (Conatel), -el ente venezolano que regula, supervisa y controla las telecomunicaciones-, en la que se le notifica que a partir de entonces sus guiones debían ser aprobados por la referida institución.
                “Quedé en shock. La carta decía que debía cambiar mi discurso opositor porque no apoyaba al Gobierno. Que ellos, desde ese momento en adelante, revisarían mi guión y me iban a decir qué podía decir y qué no. Fue sorprendente”. Aún consternada se repite: “nunca pensé que algún día me iban a apagar la voz en mi propia tierra”.
                Ese día, con esa carta amenazante como un fusil, ‘Lo que viene conviene’ transmitió por última vez.
                La burbuja
                Para esta joven profesional fue un golpe duro verse arrinconada por un gobierno que no respeta las libertades, mucho menos la de expresión. Y luego de pensarlo, tomó una de las decisiones más difíciles de los últimos tiempos para todos los venezolanos: emigrar. 
                Su destino fue España, a donde llegó en mayo de 2013 motivada no solo por la situación de Venezuela sino por una conexión que afirma sentir con la madre patria desde hace mucho tiempo. “Siempre tuve a España en mi corazón, no sé por qué. Hay algo del destino”.
                La lucha de Rebeca fue incesable porque aunque le tocó volver a empezar, no estaba dispuesta a dejar su pasión a un lado. Así que desde que llegó, comenzó a trabajar en una productora como asistente de producción, en Madrid e Ibiza. 
                “Me metí como en una burbuja para obviar todo lo que estaba viviendo y la situación en Venezuela. Haber dejado no solo mi trabajo sino también a mi familia, mi país, y reducir todo a una maleta y algo de dinero en el bolsillo, fue difícil. Así que me entregué a esta productora que me dio la oportunidad y estuve colaborando para grandes eventos. Realmente lo que quería obviar era ese dolor, esa depresión y esa nostalgia de haberlo dejado todo”, dijo seguido de un suspiro.
                Afirmó que no es fácil emigrar. “A veces queremos tapar el sol con un dedo trabajando sin cesar pero la realidad es que estar lejos de tu país es un cúmulo de emociones que además no tenemos con quien compartirlas porque nos vemos solos en un país donde no conocemos a nadie”. Confiesa que, a los meses, tuvo que realizar terapia para ayudarse durante el proceso.
                Rebeca comenzó de nuevo y aunque conserva “una nostalgia eterna” por la Venezuela que fue y que difícilmente vuelva a ser, admite sentirse muy a gusto en España, sobre todo, en Andalucía. “Me siento muy cercana. Yo creo que en otra vida fui española”, dice entre risas. Resalta además estar muy agradecida porque “España no solo me abrió las puertas a mí sino a muchos venezolanos. Nos ha dado la mano. Siento algo muy bonito por España”.
                Su cercanía con el país europeo también se debe al amor. “Hay ciudades que me gustan mucho más que otras. Cádiz, me encanta. Bueno, el hombre que me enamoró es gaditano”, asevera.
                Ese hombre, hoy su pareja, ha sido la clave fundamental para los sueños de Rebeca. Ha sido  quien a lo largo de estos años, se ha enamorado no solo del carisma, los valores y la transparente personalidad de la venezolana, sino también de su carrera profesional y sus proyectos.
                Luego de haber trabajado como asistente de producción, Rebeca fue contactada por una productora internacional para ser la imagen y conductora de habla hispana de Show Business Extra, un programa transmitido desde España para Estados Unidos y otros países de Latinoamérica. A través de este trabajo, conoce de Global Gift Foundation, una fundación dedicada a la ayuda de niños, mujeres y familias en situación de necesidad, mediante campañas y alianzas de colaboración; con la que sintió una conexión total.
                Tras terminar su contrato con Show Business TV, Rebeca le propone al equipo de Global Gift realizar un programa de televisión en el que se mostrara la loable labor de esta organización sin fines de lucro, recogiendo y transmitiendo los momentos más especiales de sus galas y eventos para la recaudación de fondos.
                El proyecto junto a la fundación era un hecho. Y Liscano ya trabajaba con su pareja en la creación de una productora, desde donde podrían realizar todo el trabajo audiovisual, que decidieron llamarla: Ribek Producciones.
                “Ribek Producciones la creamos juntos. Él ha sido un gran apoyo para la realización de mis sueños en España. Con el tiempo, se enamoró de la dirección y la producción creativa, y juntos decidimos avanzar en este proyecto de pareja que es como un hijo para nosotros”.
                La productora nació en 2016, con el fin de generar contenidos mediante programas de televisión, eventos y spots publicitarios, entre otros productos audiovisuales. Y aunque al principio, era un equipo pequeño que incluso se reunían en casas para editar; hoy por hoy Ribek Producciones cuenta con su propia oficina, equipos de alta tecnología y un recurso humano muy profesional.
                Uno de los primeros eventos, recuerda Rebeca, fue el Marbella Fashion Show 2016, un desfile de moda que contó con cuatro pasarelas para exhibir ropa deportiva, de baño, moda casual y diseños de fantasía de distintos diseñadores; y que estuvo conducido por Javier “Poty” Castillo y su persona. 
                Desde entonces, Ribek Producciones no se detiene en su ascenso; tampoco lo hace Rebeca, quien se desempeña como host en diversas galas y alfombras rojas con Star Lite. Entre tanto, Ribek Producciones se proyecta como una destacable productora de Marbella y España, que además tiene la oportunidad de generar empleo. “Hemos trabajado con mucha gente linda, preparada; y también me complace decir que tenemos a tres venezolanos trabajando con nosotros. Siempre intento involucrar a venezolanos, es una de las formas en las que puedo sumar un granito de arena”.
                De la nostalgia a la acción
                Rebeca no está segura de que los venezolanos puedan recuperarse de la nostalgia que significa estar fuera de su país por un gobierno que ha asfixiado a cada habitante, a cada hombre, cada mujer y cada niño que aún están en el país petrolero.
                Sin embargo, ese sentimiento ha sido el impulso para sumarse a la Asociación de Venezolanos Emprendedores en Málaga (AVEM), donde se desempeña como vicepresidenta, “en ese afán de sentir que puedo ayudar a mis hermanos venezolanos”.
                La Asociación trabaja en la recaudación de fondos para enviar ayuda a Venezuela y lo realiza mediante diversas actividades como conciertos y eventos de gastronomía típica venezolana. “Trabajamos sin ningún tipo de recursos económicos, sin embargo hemos logrado recaudar lo suficiente para ayudar a 8.000 niños de distintos comedores infantiles en Venezuela para garantizarles, al menos, el desayuno y el almuerzo”.  
                El trabajo de Rebeca es social. Tanto su aporte como imagen y host de Global Gift así como en AVEM son ad honorem, una forma de sensibilizarse con los más necesitados desde su trinchera de lucha.
                “No solo he aportado con tiempo, dinero o imagen sino con esas ganas profundas de rescatar a Venezuela de alguna forma y con la frustración, a la vez, de no poder hacer nada para cambiar la realidad de nuestro país”.
                Rebeca es una auténtica venezolana, de esas que podrían ser calificadas como “embajadora de Venezuela”, no por razones diplomáticas, sino por ser ejemplo del verdadero tricolor, ese que se transmite a través de los valores, la educación y una sonrisa pintada en el rostro a pesar de las adversidades.
            </h3>
        </>
    )
}
